branches:
  only:
  - master

assembly_info:
  patch: false

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

build_script:
  - ps: ./build.ps1
  
artifacts:
 - path: '**\POGOProtos.*.nupkg'

cache:
  - '%USERPROFILE%\.nuget\packages'